export default{
    loginStateDelete(state){
        state.Loginstate=false
    },
    loginStateActive(state){
        state.Loginstate=true
    },
    talkingUserState(state,x){
        state.talkingUsername=x
        state.talkListstate=true
    },
    talkingUserStateClose(state){
        state.talkingUsername=''
        state.talkListstate=false
    },
    addNextPerson(state,x){
        state.nextpersonmeg=x
    },
    messageTagclear(state,x){
        state.clearPersonname=x
    },
    pushNewPersonMessage(state,x){
        state.newpersonMessage=x
    },
    changeTalkListNumber(state,x){
        state.talklistnumber=x
    },
    setTalkNumberTop(state,x){
        state.talknumbertop=x
    }
}
